// <auto-generated />
using System;
using DbCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBCore.Migrations
{
    [DbContext(typeof(DocumentDbContext))]
    [Migration("20220828020421_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Common.BL.Documentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Estado1")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("estado1");

                    b.Property<string>("Estado2")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("estado2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_emision");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("nombre_empresa");

                    b.Property<int>("NumeroDocumento")
                        .HasColumnType("int")
                        .HasColumnName("numero_documento");

                    b.Property<string>("RutEmisor")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("rut_emisor");

                    b.Property<string>("RutReceptor")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("rut_receptor");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("tipo_documento");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.Property<int>("ValorIVA")
                        .HasColumnType("int")
                        .HasColumnName("valor_iva");

                    b.Property<int>("ValorNeto")
                        .HasColumnType("int")
                        .HasColumnName("valor_neto");

                    b.HasKey("Id");

                    b.ToTable("documentos");
                });

            modelBuilder.Entity("Common.BL.EstadosSII", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_consulta");

                    b.Property<int>("NumeroDocumento")
                        .HasColumnType("int")
                        .HasColumnName("numero_documento");

                    b.Property<string>("RespuestaCodigoSII")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("respuesta_codigo_sii");

                    b.Property<string>("RespuestaDescripSII")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("respuesta_descrip_sii");

                    b.Property<string>("RutReceptor")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("rut_receptor");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("estados_sii");
                });

            modelBuilder.Entity("Common.BL.EstadosSII", b =>
                {
                    b.HasOne("Common.BL.Documentos", "Documento")
                        .WithMany("LineasEstado")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("Common.BL.Documentos", b =>
                {
                    b.Navigation("LineasEstado");
                });
#pragma warning restore 612, 618
        }
    }
}
